@startuml VendingMachine
state "VendingMachine State" as Chickensoft_LogicBlocks_Example_VendingMachine_State {
  state "SelectionEditable" as Chickensoft_LogicBlocks_Example_VendingMachine_SelectionEditable {
    state "Idle" as Chickensoft_LogicBlocks_Example_VendingMachine_Idle
    state "TransactionActive" as Chickensoft_LogicBlocks_Example_VendingMachine_TransactionActive {
      state "TransactionStarted" as Chickensoft_LogicBlocks_Example_VendingMachine_TransactionStarted
    }
  }
  state "Vending" as Chickensoft_LogicBlocks_Example_VendingMachine_Vending
}

Chickensoft_LogicBlocks_Example_VendingMachine_Idle --> Chickensoft_LogicBlocks_Example_VendingMachine_Idle : PaymentReceived
Chickensoft_LogicBlocks_Example_VendingMachine_SelectionEditable --> Chickensoft_LogicBlocks_Example_VendingMachine_SelectionEditable : SelectionEntered
Chickensoft_LogicBlocks_Example_VendingMachine_SelectionEditable --> Chickensoft_LogicBlocks_Example_VendingMachine_TransactionStarted : SelectionEntered
Chickensoft_LogicBlocks_Example_VendingMachine_TransactionActive --> Chickensoft_LogicBlocks_Example_VendingMachine_Idle : TransactionTimedOut
Chickensoft_LogicBlocks_Example_VendingMachine_TransactionActive --> Chickensoft_LogicBlocks_Example_VendingMachine_TransactionActive : PaymentReceived
Chickensoft_LogicBlocks_Example_VendingMachine_TransactionActive --> Chickensoft_LogicBlocks_Example_VendingMachine_Vending : PaymentReceived
Chickensoft_LogicBlocks_Example_VendingMachine_TransactionStarted --> Chickensoft_LogicBlocks_Example_VendingMachine_TransactionStarted : SelectionEntered
Chickensoft_LogicBlocks_Example_VendingMachine_Vending --> Chickensoft_LogicBlocks_Example_VendingMachine_Idle : VendingCompleted

Chickensoft_LogicBlocks_Example_VendingMachine_Idle : OnEnter → ClearTransactionTimeOutTimer
Chickensoft_LogicBlocks_Example_VendingMachine_Idle : OnPaymentReceived → MakeChange
Chickensoft_LogicBlocks_Example_VendingMachine_SelectionEditable : OnSelectionEntered → RestartTransactionTimeOutTimer
Chickensoft_LogicBlocks_Example_VendingMachine_TransactionActive : OnEnter → RestartTransactionTimeOutTimer
Chickensoft_LogicBlocks_Example_VendingMachine_TransactionActive : OnPaymentReceived → MakeChange, RestartTransactionTimeOutTimer, TransactionCompleted
Chickensoft_LogicBlocks_Example_VendingMachine_TransactionActive : OnTransactionTimedOut → MakeChange
Chickensoft_LogicBlocks_Example_VendingMachine_TransactionStarted : OnEnter → TransactionStarted
Chickensoft_LogicBlocks_Example_VendingMachine_TransactionStarted : OnSelectionEntered → RestartTransactionTimeOutTimer
Chickensoft_LogicBlocks_Example_VendingMachine_Vending : OnEnter → BeginVending

[*] --> Chickensoft_LogicBlocks_Example_VendingMachine_Idle
@enduml