@startuml Timer
state "Timer State" as Chickensoft_LogicBlocks_Tutorial_Timer_State {
  state "PoweredOff" as Chickensoft_LogicBlocks_Tutorial_Timer_State_PoweredOff
  state "PoweredOn" as Chickensoft_LogicBlocks_Tutorial_Timer_State_PoweredOn {
    state "Idle" as Chickensoft_LogicBlocks_Tutorial_Timer_State_PoweredOn_Idle
    state "Countdown" as Chickensoft_LogicBlocks_Tutorial_Timer_State_PoweredOn_Countdown
    state "Beeping" as Chickensoft_LogicBlocks_Tutorial_Timer_State_PoweredOn_Beeping
  }
}

Chickensoft_LogicBlocks_Tutorial_Timer_State_PoweredOff --> Chickensoft_LogicBlocks_Tutorial_Timer_State_PoweredOn_Idle : PowerButtonPressed
Chickensoft_LogicBlocks_Tutorial_Timer_State_PoweredOn --> Chickensoft_LogicBlocks_Tutorial_Timer_State_PoweredOff : PowerButtonPressed
Chickensoft_LogicBlocks_Tutorial_Timer_State_PoweredOn_Beeping --> Chickensoft_LogicBlocks_Tutorial_Timer_State_PoweredOn_Idle : StartStopButtonPressed
Chickensoft_LogicBlocks_Tutorial_Timer_State_PoweredOn_Countdown --> Chickensoft_LogicBlocks_Tutorial_Timer_State_PoweredOn_Beeping : TimeElapsed
Chickensoft_LogicBlocks_Tutorial_Timer_State_PoweredOn_Countdown --> Chickensoft_LogicBlocks_Tutorial_Timer_State_PoweredOn_Countdown : TimeElapsed
Chickensoft_LogicBlocks_Tutorial_Timer_State_PoweredOn_Countdown --> Chickensoft_LogicBlocks_Tutorial_Timer_State_PoweredOn_Idle : StartStopButtonPressed
Chickensoft_LogicBlocks_Tutorial_Timer_State_PoweredOn_Idle --> Chickensoft_LogicBlocks_Tutorial_Timer_State_PoweredOn_Countdown : StartStopButtonPressed
Chickensoft_LogicBlocks_Tutorial_Timer_State_PoweredOn_Idle --> Chickensoft_LogicBlocks_Tutorial_Timer_State_PoweredOn_Idle : ChangeDuration

Chickensoft_LogicBlocks_Tutorial_Timer_State_PoweredOn_Beeping : OnEnter → PlayBeepingSound
Chickensoft_LogicBlocks_Tutorial_Timer_State_PoweredOn_Beeping : OnExit → StopBeepingSound

[*] --> Chickensoft_LogicBlocks_Tutorial_Timer_State_PoweredOff
@enduml