@startuml GenericLogicBlock
state "GenericLogicBlock State" as Chickensoft_LogicBlocks_DiagramGenerator_Tests_TestCases_MyGenericType_GenericLogicBlock_State {
  state "StateOne" as Chickensoft_LogicBlocks_DiagramGenerator_Tests_TestCases_MyGenericType_GenericLogicBlock_StateOne
  state "StateTwo" as Chickensoft_LogicBlocks_DiagramGenerator_Tests_TestCases_MyGenericType_GenericLogicBlock_StateTwo
}

Chickensoft_LogicBlocks_DiagramGenerator_Tests_TestCases_MyGenericType_GenericLogicBlock_StateOne --> Chickensoft_LogicBlocks_DiagramGenerator_Tests_TestCases_MyGenericType_GenericLogicBlock_StateTwo : InputOne
Chickensoft_LogicBlocks_DiagramGenerator_Tests_TestCases_MyGenericType_GenericLogicBlock_StateTwo --> Chickensoft_LogicBlocks_DiagramGenerator_Tests_TestCases_MyGenericType_GenericLogicBlock_StateOne : InputTwo
[*] --> Chickensoft_LogicBlocks_DiagramGenerator_Tests_TestCases_MyGenericType_GenericLogicBlock_State
@enduml