@startuml Patterns
state "Patterns State" as Chickensoft_LogicBlocks_DiagramGenerator_Tests_TestCases_Patterns_State {
  state "One" as Chickensoft_LogicBlocks_DiagramGenerator_Tests_TestCases_Patterns_State_One
  state "Two" as Chickensoft_LogicBlocks_DiagramGenerator_Tests_TestCases_Patterns_State_Two
  state "Three" as Chickensoft_LogicBlocks_DiagramGenerator_Tests_TestCases_Patterns_State_Three
}

Chickensoft_LogicBlocks_DiagramGenerator_Tests_TestCases_Patterns_State --> Chickensoft_LogicBlocks_DiagramGenerator_Tests_TestCases_Patterns_State_One : SetMode
Chickensoft_LogicBlocks_DiagramGenerator_Tests_TestCases_Patterns_State --> Chickensoft_LogicBlocks_DiagramGenerator_Tests_TestCases_Patterns_State_Three : SetMode
Chickensoft_LogicBlocks_DiagramGenerator_Tests_TestCases_Patterns_State --> Chickensoft_LogicBlocks_DiagramGenerator_Tests_TestCases_Patterns_State_Two : SetMode
[*] --> Chickensoft_LogicBlocks_DiagramGenerator_Tests_TestCases_Patterns_State_One
@enduml