@startuml SingleState
state "SingleState State" as Chickensoft_LogicBlocks_Generator_Tests_SingleState_State

Chickensoft_LogicBlocks_Generator_Tests_SingleState_State --> Chickensoft_LogicBlocks_Generator_Tests_SingleState_State : MyInput

Chickensoft_LogicBlocks_Generator_Tests_SingleState_State : OnEnter → MyOutput
Chickensoft_LogicBlocks_Generator_Tests_SingleState_State : OnExit → MyOutput
Chickensoft_LogicBlocks_Generator_Tests_SingleState_State : OnMyInput → MyOutput

[*] --> Chickensoft_LogicBlocks_Generator_Tests_SingleState_State
@enduml