namespace Chickensoft.LogicBlocks;

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization.Metadata;
using Chickensoft.LogicBlocks.Types;

/// <summary>
/// Represents a metatype — a type that helps describe another type.
/// </summary>
public interface IMetatype {
  /// <summary>
  /// Create the JsonTypeInfo needed by System.Text.Json for this metatype.
  /// </summary>
  /// <param name="registry">Type registry generated by the LogicBlocks
  /// generator.</param>
  /// <param name="options">Json serializer options.</param>
  JsonTypeInfo CreateJsonTypeInfo(
    ITypeRegistry registry, JsonSerializerOptions options
  );

  /// <summary>
  /// Properties on the type. Only non-partial properties marked with
  /// attributes on the current type are included. To get all of the properties,
  /// including the inherited properties from any base metatypes, see the
  /// <see cref="LogicBlockTypes.GetProperties"/> method.
  /// </summary>
  IList<LogicProp> Properties { get; }

  /// <summary>Attributes applied to the type itself.</summary>
  IDictionary<Type, Attribute[]> Attributes { get; }

  /// <summary>
  /// List of mixins applied to the type, in the order that they were applied.
  /// </summary>
  IList<Type> Mixins { get; }

  /// <summary>
  /// Map of mixin handler invocation functions by mixin type.
  /// </summary>
  IDictionary<Type, Action<object>> MixinHandlers { get; }

  /// <summary>
  /// Metatype identifier. This will be used as the type discriminator for
  /// serialization and deserialization if used with LogicBlock's serialization
  /// utilities.
  /// </summary>
  string Id { get; }
}
