@startuml LightSwitch
state "LightSwitch State" as Chickensoft_LogicBlocks_Generator_Tests_LightSwitch_State {
  state "PoweredOn" as Chickensoft_LogicBlocks_Generator_Tests_LightSwitch_State_PoweredOn
  state "Powered" as Chickensoft_LogicBlocks_Generator_Tests_LightSwitch_State_Powered
}

Chickensoft_LogicBlocks_Generator_Tests_LightSwitch_State_Powered --> Chickensoft_LogicBlocks_Generator_Tests_LightSwitch_State_PoweredOn : Toggle
Chickensoft_LogicBlocks_Generator_Tests_LightSwitch_State_PoweredOn --> Chickensoft_LogicBlocks_Generator_Tests_LightSwitch_State_Powered : Toggle

Chickensoft_LogicBlocks_Generator_Tests_LightSwitch_State_Powered : OnEnter → StatusChanged
Chickensoft_LogicBlocks_Generator_Tests_LightSwitch_State_PoweredOn : OnEnter → StatusChanged

[*] --> Chickensoft_LogicBlocks_Generator_Tests_LightSwitch_State_Powered
@enduml