@startuml LightSwitch
state "LightSwitch State" as Chickensoft_LogicBlocks_Generator_Tests_LightSwitch_State {
  state "On" as Chickensoft_LogicBlocks_Generator_Tests_LightSwitch_State_On
  state "Off" as Chickensoft_LogicBlocks_Generator_Tests_LightSwitch_State_Off
}

Chickensoft_LogicBlocks_Generator_Tests_LightSwitch_State_Off --> Chickensoft_LogicBlocks_Generator_Tests_LightSwitch_State_On : Toggle
Chickensoft_LogicBlocks_Generator_Tests_LightSwitch_State_On --> Chickensoft_LogicBlocks_Generator_Tests_LightSwitch_State_Off : Toggle

[*] --> Chickensoft_LogicBlocks_Generator_Tests_LightSwitch_State_Off
@enduml