@startuml LightSwitchAdvanced
state "LightSwitchAdvanced State" as Chickensoft_LogicBlocks_Generator_Tests_LightSwitchAdvanced_State {
  state "On" as Chickensoft_LogicBlocks_Generator_Tests_LightSwitchAdvanced_State_On {
    Chickensoft_LogicBlocks_Generator_Tests_LightSwitchAdvanced_State_On : OnEnter → StatusChanged
  }
  state "Off" as Chickensoft_LogicBlocks_Generator_Tests_LightSwitchAdvanced_State_Off {
    Chickensoft_LogicBlocks_Generator_Tests_LightSwitchAdvanced_State_Off : OnEnter → StatusChanged
  }
}

Chickensoft_LogicBlocks_Generator_Tests_LightSwitchAdvanced_State_Off --> Chickensoft_LogicBlocks_Generator_Tests_LightSwitchAdvanced_State_On : Toggle
Chickensoft_LogicBlocks_Generator_Tests_LightSwitchAdvanced_State_On --> Chickensoft_LogicBlocks_Generator_Tests_LightSwitchAdvanced_State_Off : Toggle

[*] --> Chickensoft_LogicBlocks_Generator_Tests_LightSwitchAdvanced_State_Off
@enduml