@startuml LightSwitch
state "LightSwitch State" as Chickensoft_LogicBlocks_Generator_Tests_LightSwitch_State {
  state "SwitchedOn" as Chickensoft_LogicBlocks_Generator_Tests_LightSwitch_State_SwitchedOn
  state "SwitchedOff" as Chickensoft_LogicBlocks_Generator_Tests_LightSwitch_State_SwitchedOff
}

Chickensoft_LogicBlocks_Generator_Tests_LightSwitch_State_SwitchedOff --> Chickensoft_LogicBlocks_Generator_Tests_LightSwitch_State_SwitchedOn : Toggle
Chickensoft_LogicBlocks_Generator_Tests_LightSwitch_State_SwitchedOn --> Chickensoft_LogicBlocks_Generator_Tests_LightSwitch_State_SwitchedOff : Toggle

[*] --> Chickensoft_LogicBlocks_Generator_Tests_LightSwitch_State_SwitchedOff
@enduml