@startuml HeaterState
state "HeaterState" as Chickensoft_LogicBlocks_DiagramGenerator_Tests_TestCases_Heater_HeaterState {
  state "Off" as Chickensoft_LogicBlocks_DiagramGenerator_Tests_TestCases_Heater_HeaterState_Off
  state "Powered" as Chickensoft_LogicBlocks_DiagramGenerator_Tests_TestCases_Heater_HeaterState_Powered {
    state "Heating" as Chickensoft_LogicBlocks_DiagramGenerator_Tests_TestCases_Heater_HeaterState_Heating
    state "Idle" as Chickensoft_LogicBlocks_DiagramGenerator_Tests_TestCases_Heater_HeaterState_Idle
  }
}

Chickensoft_LogicBlocks_DiagramGenerator_Tests_TestCases_Heater_HeaterState --> Chickensoft_LogicBlocks_DiagramGenerator_Tests_TestCases_Heater_HeaterState : TargetTempChanged
Chickensoft_LogicBlocks_DiagramGenerator_Tests_TestCases_Heater_HeaterState_Heating --> Chickensoft_LogicBlocks_DiagramGenerator_Tests_TestCases_Heater_HeaterState_Heating : AirTempSensorChanged
Chickensoft_LogicBlocks_DiagramGenerator_Tests_TestCases_Heater_HeaterState_Heating --> Chickensoft_LogicBlocks_DiagramGenerator_Tests_TestCases_Heater_HeaterState_Idle : AirTempSensorChanged
Chickensoft_LogicBlocks_DiagramGenerator_Tests_TestCases_Heater_HeaterState_Idle --> Chickensoft_LogicBlocks_DiagramGenerator_Tests_TestCases_Heater_HeaterState_Heating : AirTempSensorChanged
Chickensoft_LogicBlocks_DiagramGenerator_Tests_TestCases_Heater_HeaterState_Idle --> Chickensoft_LogicBlocks_DiagramGenerator_Tests_TestCases_Heater_HeaterState_Idle : AirTempSensorChanged
Chickensoft_LogicBlocks_DiagramGenerator_Tests_TestCases_Heater_HeaterState_Off --> Chickensoft_LogicBlocks_DiagramGenerator_Tests_TestCases_Heater_HeaterState_Heating : TurnOn
Chickensoft_LogicBlocks_DiagramGenerator_Tests_TestCases_Heater_HeaterState_Off --> Chickensoft_LogicBlocks_DiagramGenerator_Tests_TestCases_Heater_HeaterState_Idle : TurnOn
Chickensoft_LogicBlocks_DiagramGenerator_Tests_TestCases_Heater_HeaterState_Powered --> Chickensoft_LogicBlocks_DiagramGenerator_Tests_TestCases_Heater_HeaterState_Off : TurnOff

Chickensoft_LogicBlocks_DiagramGenerator_Tests_TestCases_Heater_HeaterState_Heating : OnAirTempSensorChanged → FinishedHeating
Chickensoft_LogicBlocks_DiagramGenerator_Tests_TestCases_Heater_HeaterState_Powered : OnEnter → Chime
@enduml
