@startuml BaseState
state "BaseState" as Chickensoft_LogicBlocks_DiagramGenerator_Tests_TestCases_Patterns_BaseState {
  state "One" as Chickensoft_LogicBlocks_DiagramGenerator_Tests_TestCases_Patterns_BaseState_One
  state "Three" as Chickensoft_LogicBlocks_DiagramGenerator_Tests_TestCases_Patterns_BaseState_Three
  state "Two" as Chickensoft_LogicBlocks_DiagramGenerator_Tests_TestCases_Patterns_BaseState_Two
}

Chickensoft_LogicBlocks_DiagramGenerator_Tests_TestCases_Patterns_BaseState --> Chickensoft_LogicBlocks_DiagramGenerator_Tests_TestCases_Patterns_BaseState_One : SetMode
Chickensoft_LogicBlocks_DiagramGenerator_Tests_TestCases_Patterns_BaseState --> Chickensoft_LogicBlocks_DiagramGenerator_Tests_TestCases_Patterns_BaseState_Three : SetMode
Chickensoft_LogicBlocks_DiagramGenerator_Tests_TestCases_Patterns_BaseState --> Chickensoft_LogicBlocks_DiagramGenerator_Tests_TestCases_Patterns_BaseState_Two : SetMode
@enduml
