@startuml BaseState
state "BaseState" as Chickensoft_LogicBlocks_DiagramGenerator_Tests_TestCases_SharedBaseLogicBlock_BaseState {
  state "Idle" as Chickensoft_LogicBlocks_DiagramGenerator_Tests_TestCases_SharedBaseLogicBlock_BaseState_Idle
  state "Running" as Chickensoft_LogicBlocks_DiagramGenerator_Tests_TestCases_SharedBaseLogicBlock_BaseState_Running
}

Chickensoft_LogicBlocks_DiagramGenerator_Tests_TestCases_SharedBaseLogicBlock_BaseState_Idle --> Chickensoft_LogicBlocks_DiagramGenerator_Tests_TestCases_SharedBaseLogicBlock_BaseState_Running : Toggle
Chickensoft_LogicBlocks_DiagramGenerator_Tests_TestCases_SharedBaseLogicBlock_BaseState_Running --> Chickensoft_LogicBlocks_DiagramGenerator_Tests_TestCases_SharedBaseLogicBlock_BaseState_Idle : Toggle

Chickensoft_LogicBlocks_DiagramGenerator_Tests_TestCases_SharedBaseLogicBlock_BaseState_Running : OnEnter → Toggled
@enduml